# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI Feature Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-matrix:
    name: Build and Test (${{ matrix.os }} ${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      QT_VERSION: '5.15.2'
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ runner.os == 'Linux' && 'linux' || runner.os == 'Windows' && 'windows' || 'mac' }}
          target: 'desktop'
          arch: ${{ runner.os == 'Linux' && 'gcc_64' || runner.os == 'Windows' && 'win64_msvc2019_64' || 'clang_64' }}
          dir: '${{ github.workspace }}/qt/'
          modules: 'qtcharts qtwebengine qttools'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libjsoncpp-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install curl openssl jsoncpp

      - name: Verify Qt Installation
        shell: bash
        run: |
          echo "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}"
          echo "Qt5_DIR: ${Qt5_DIR}"
          echo "QTDIR: ${QTDIR}"
          
          # Verify Qt5Config.cmake exists
          if [ -n "${CMAKE_PREFIX_PATH}" ]; then
            echo "Searching for Qt5Config.cmake in CMAKE_PREFIX_PATH..."
            find "${CMAKE_PREFIX_PATH}" -name "Qt5Config.cmake" -type f 2>/dev/null | head -3 || echo "Qt5Config.cmake not found in CMAKE_PREFIX_PATH"
          fi

      - name: Configure CMake
        shell: bash
        run: |
          echo "Configuring CMake with BUILD_TYPE=${{ env.BUILD_TYPE }}"
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        shell: bash
        run: |
          echo "Building project..."
          cmake --build build --config ${{ env.BUILD_TYPE }} --verbose

      - name: Debug Build Directory
        run: ls -la build/

      - name: Run tests with verbose output
        run: ctest --test-dir build --output-on-failure --verbose -C ${{ env.BUILD_TYPE }}
        continue-on-error: true

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/Testing/Temporary/LastTest.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/

  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Run clang-format
        run: |
          find . -regex '.*\.[ch]pp' -exec clang-format --dry-run --Werror {} +

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --error-exitcode=1 --std=c++17 --suppress=missingIncludeSystem .