# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CMake Build (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt5
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          modules: 'qtbase qttools'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure CMake
        run: >
          cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH="${{ env.Qt5_DIR }}"

      - name: Build
        run: cmake --build build --config Release

      - name: Test (if tests exist)
        run: |
          if (Test-Path build/Debug/ctest.exe) { ctest --test-dir build --output-on-failure }
        shell: pwsh
